.circleci/config.yml
=> Upgrades QEMU to v2.11.0

base/rootfs/usr/lib/hassio-addons/modules/api.sh
After some discussion, we rename this.
=> Rename Hassio API token

.gitlab-ci.yml
=> :sparkles: Adds Gitlab CI

README.md
Fixes the commits badge in the repository README
=> Fix commits badge in README

base/Dockerfile
=> :arrow_up: Upgrades ca-certificates to 20200601~deb10u2

base/Dockerfile
=> :arrow_up: Upgrades tzdata to 2021a-0+deb10u1

base/Dockerfile, base/build.json
Upgrade add-on base image to Debian Buster 20210208
=> Upgrade add-on base image to Debian Buster 20210208

base/Dockerfile
Upgrade S6 Overlay to v2.2.0.3
=> Upgrade S6 Overlay to v2.2.0.3

base/Dockerfile, base/build.json
Upgrade Debian to buster-20210329-slim
=> ⬆️ Upgrade Debian to buster-20210329-slim

base/Dockerfile, base/build.json
https://www.debian.org/News/2021/20210814
=> ⬆️ Upgrades Debian to Bullseye 20210816

base/Dockerfile, base/build.json
Upgrades base image to Debian Bullseye 20210902
=> ⬆️ Upgrades base image to Debian Bullseye 20210902

.github/workflows/ci.yaml, .github/workflows/deploy.yaml
=> 🔥 Remove no longer needed static qemu injection

base/Dockerfile, base/build.json
Upgrades Debian to Bullseye 20211011
=> :arrow_up: Upgrades Debian to Bullseye 20211011

base/Dockerfile
Upgrades curl to 7.74.0-1.3+deb11u1
=> ⬆️ Upgrades curl to 7.74.0-1.3+deb11u1

base/Dockerfile
Upgrades tzdata to 2021a-1+deb11u2
=> ⬆️ Upgrades tzdata to 2021a-1+deb11u2

base/Dockerfile, base/build.yaml
Upgrades Debian to Bullseye 20211220
=> :arrow_up: Upgrades Debian to Bullseye 20211220

base/Dockerfile, base/build.yaml
Upgrades Debian to Bullseye 20220228
=> :arrow_up: Upgrades Debian to Bullseye 20220228

.github/workflows/deploy.yaml, base/build.yaml
Sign base image with Codenotary Community Attestation Service (CAS)
=> :lock: Sign image with Codenotary Community Attestation Service (CAS)

base/Dockerfile
Upgrades tzdata to 2021a-1+deb11u3
=> ⬆️ Upgrades tzdata to 2021a-1+deb11u3

base/Dockerfile, base/build.yaml
Upgrades Debian to Bullseye 20220328
=> :arrow_up: Upgrades Debian to Bullseye 20220328

base/Dockerfile, base/build.yaml
Upgrades Debian to Bullseye 20220527
=> :arrow_up: Upgrades Debian to Bullseye 20220527

base/Dockerfile
https://github.com/just-containers/s6-overlay/compare/v3.1.0.1...v3.1.1.0
=> ⬆️ Upgrades s6-overlay to v3.1.1.0

base/Dockerfile, base/build.yaml
Upgrades Debian to Bullseye 20220711
=> :arrow_up: Upgrades Debian to Bullseye 20220711

base/Dockerfile
Upgrades bash to 5.1-2+deb11u1
=> ⬆️ Upgrades bash to 5.1-2+deb11u1

base/Dockerfile
Upgrades xz-utils to 5.2.5-2.1~deb11u1
=> ⬆️ Upgrades xz-utils to 5.2.5-2.1~deb11u1

base/Dockerfile, base/build.yaml
Upgrades Debian to Bullseye 20220801
=> :arrow_up: Upgrades Debian to Bullseye 20220801

base/Dockerfile
Upgrades curl to 7.74.0-1.3+deb11u2
=> ⬆️ Upgrades curl to 7.74.0-1.3+deb11u2

base/Dockerfile, base/build.yaml
=> :arrow_up: Upgrades Debian to Bullseye 20220912

base/Dockerfile, base/build.yaml
=> :arrow_up: Upgrades Debian to Bullseye 20221024

base/Dockerfile, base/s6-overlay/etc/s6-rc/scripts/base-addon-banner, base/s6-overlay/etc/s6-rc/scripts/base-addon-log-level, base/s6-overlay/etc/s6-rc/scripts/base-addon-timezone, base/s6-overlay/etc/s6-rc/sources/base-addon-banner/type, base/s6-overlay/etc/s6-rc/sources/base-addon-banner/up, base/s6-overlay/etc/s6-rc/sources/base-addon-log-level/type, base/s6-overlay/etc/s6-rc/sources/base-addon-log-level/up, base/s6-overlay/etc/s6-rc/sources/base-addon-timezone/type, base/s6-overlay/etc/s6-rc/sources/base-addon-timezone/up
Migrates the old style S6-overlay to the new style.
Since this is a base image, this hooks directly into s6-overlay's packages. 
Add-ons building on top of this aren't impacted.
=> :hammer: Migrate old-style base scripts s6-rc

LICENSE.md, README.md, base/Dockerfile
=> :fireworks: Updates maintenance/license year to 2023

base/Dockerfile, base/build.yaml
=> :arrow_up: Upgrades Debian to Bullseye 20230208

base/Dockerfile
=> ⬆️ Upgrades curl to 7.74.0-1.3+deb11u7

.github/dependabot.yaml, .github/renovate.json, base/Dockerfile, base/build.yaml
=> Add Renovate for dependency management

.github/renovate.json
=> :shirt: Better match debian packages in Renovate
